### ISSUE TITLE
Identify a branch that isn't set upstream

### ISSUE THREAD

**Issue by michaeldfallen** [michaeldfallen/git-prompt#1]
If a branch isn't set upstream (i.e. isn't tracking a remote branch) then the remote_branch_name returns ``and so all the`remote_ahead..`/`remote_behind..` calls return nothing. 

That isn't particularly informative. Would be useful to have a function that tells you if a local branch is tracking and can be used in the prompt to identify a branch that is local only.

**Comment by michaeldfallen** [comment]
This has been fixed. Both `bash_color_remote_commits` and `zsh_color_remote_commits` now return:

```
git:(upstream ⚡ my-branch)
```

If the branch is not upstream.

**Comment by jackmaney** [comment]
First of all, thank you for releasing this library. I've been looking off and on for a simple to use, 100% bash solution to this.

I was about to start an issue, but I think this one touches on it... I'm in a repo whose only branches (via `git remote -a`) are `master` and `remotes/origin/master`. Also, these branches are completely in sync (ie `git status` reveals that the working directory is clean). 

However, the prompt is still `git:(upstream ⚡ master)`.

**Comment by michaeldfallen** [comment]
Thanks for the kind words. That this has gone from pet project to full blown used by people thing is amazing. 

I do think there are a few problems with tracking branches, one example is when you have two remotes and checkout master on those remotes to two different locations. 

can you run `git remote -a -vvv` and comment with the results? if master tracks correctly this shouldn't happen so I'd like to know what's going on too.
