### ISSUE TITLE
Calling Formula.sha1 is deprecated!

### ISSUE THREAD

**Issue by orangecoding** [michaeldfallen/git-prompt#105]
If using Git-Radar with homebrew on macOS 10.11.6, I'll always get the following message if I try to brew update/upgrade

`Warning: Calling Formula.sha1 is deprecated!
Use Formula.sha256 instead.
/usr/local/Library/Taps/michaeldfallen/homebrew-formula/git-radar.rb:7:in`class:GitRadar'
Please report this to the michaeldfallen/formula tap!`

**Comment by orangecoding** [comment]
Problem is resolved by this:

`cd "$(brew --repo)" && git fetch && git reset --hard origin/master && brew update`

**Comment by michaeldfallen** [comment]
This was fixed in https://github.com/michaeldfallen/git-radar/issues/104, about 1 month ago. Likely you need to update and upgrade. 

Closing
