### ISSUE TITLE
nohup redirection is presented with every prompt.

### ISSUE THREAD

**Issue by dbrowne** [michaeldfallen/git-prompt#16]
This is a quick fix: line 80 of git-radar
nohup $dot/fetch.sh 2>/dev/null &

Redirecting stderr

**Comment by michaeldfallen** [comment]
Yeah, we've been discussing this in https://github.com/michaeldfallen/git-radar/issues/13. I'm afk at the moment but I'll merge a pull request that does this. Thanks.

**Comment by kenhkelly** [comment]
@dbrowne Have any idea how I could get out of this endless loop?

Edit: I managed to figure it out. Looking forward to that merge!

**Comment by michaeldfallen** [comment]
Fixed in #25
