### ISSUE TITLE
Make it an oh-my-zsh theme?

### ISSUE THREAD

**Issue by ahmetb** [michaeldfallen/git-prompt#21]

**Comment by shkm** [comment]
:+1:  This would be awesome :).

**Comment by oceansize** [comment]
+1

**Comment by therzka** [comment]
+1

**Comment by bumaociyuan** [comment]
+1

**Comment by halcyon** [comment]
+1

**Comment by robertmircea** [comment]
+1

**Comment by eibreans** [comment]
+1

**Comment by hasantayyar** [comment]
+1

Also there is a workout about this issue https://github.com/robbyrussell/oh-my-zsh/issues/4288

**Comment by Mgldvd** [comment]
+1

**Comment by oryband** [comment]
:+1:

**Comment by Thermatix** [comment]
I realise this is an old issue but I wanted to add to it. I think that git-rader should be a separate plugin but can tell oh-my-zsh that it exists then any theme that has some kind of git segment could instead use git-rader over any internal implementation, that way they can integrate it with there theme's. 

That way you can use whatever theme you want and still have access to this wonderful plugin, plus  if you add an api for appearance it would fit in easier.

**Comment by ahmetb** [comment]
Look at all these +1s man

**Comment by michaeldfallen** [comment]
Yup, too bad I don't use Oh-my-zsh and so can't reliably do this. You could though if you want, I'll happily accept a pull request for any changes needed.
