### ISSUE TITLE
Prompt not updating - OSX - zsh

### ISSUE THREAD

**Issue by dsandstrom** [michaeldfallen/git-prompt#28]
The prompt doesn't update when I change branches, make changes, or anything else.  However, it does work when using bash.  The only way I can get it to change is by opening a new shell window or running `exec $SHELL`.

**Comment by olyckne** [comment]
Same for me on OSX El Capitan.

**Comment by michaeldfallen** [comment]
Probably your zsh config isn't set correctly to re-execute everytime the prompt rerenders. My `.zshrc` prompt part is here: [dotfiles/zsh/prompt.zsh#L11](https://github.com/michaeldfallen/dotfiles/blob/master/zsh/prompt.zsh#L11).

The important part is the:

``` bash
export PROMPT=$'$(foo)'
```

part. The `$'` ensures that Zsh re-executes the functions on render. I think alternatively you can do:

``` zsh
export PROMPT="\$(foo)"
```

The `\` would escape the `$` and so prevent the function from being executed until Zsh `eval`s the PROMPT on render.

**Comment by peteringram0** [comment]
I was seeing this issue also. +1 for the fix above

**Comment by olyckne** [comment]
I just copy pasted from the readme:
`export PROMPT="$PROMPT$(git-radar --zsh --fetch) "`

escaping the $ did work:
`export PROMPT="$PROMPT\$(git-radar --zsh --fetch) "`

**Comment by dsandstrom** [comment]
Thanks the quick reply.  Sounds like you have found a fix.  Unfortunately,
I won't be able to confirm until Monday.

**Comment by michaeldfallen** [comment]
@olyckne ahh, I've messed up the readme. OK, I'll close this issue and open a fresh one to describe the problem. Afk at the moment but I'll rewrite it tonight.
