### ISSUE TITLE
Show whether anything is stashed 

### ISSUE THREAD

**Issue by lorensr** [michaeldfallen/git-prompt#31]
Sometimes I forget that I have something stashed, and later come back to the problem and wind up rewriting things. Would be nice to see that I have something stashed. Maybe just a single character, or a number 1-9+ of how many things are stashed.

**Comment by tnguyen14** [comment]
+1 for this!

**Comment by cbandera** [comment]
+1
What kind of symbol would you use? Maybe an [open box](http://unicode-table.com/en/2423/)?
It could be as easy as:

``` bash
bash_stash_status() {
  local number_stashes="$(git stash list | wc -l)"
  if [ $number_stashes -gt 0 ]; then
    printf " $number_stashes\x01\033[1;33m\x02␣\x01\033[0m\x02)"
  fi
}
```

**Comment by anaran** [comment]
> What kind of symbol would you use? Maybe an open box?

How about `=` resembling a stack of stashed content?

**Comment by cbandera** [comment]
> How about = resembling a stack of stashed content?

Yes, I like that. Do you happen to use zsh and could test [this code](https://github.com/cbandera/git-radar/commit/2cfe557beb7fec2e67ea8cd0096eeff0be14b00f) before I create a pull request?

**Comment by michaeldfallen** [comment]
Nice idea. I'm always tempted to try using the combining diacritical marks to "draw" an icon. Something like:

<img width="35" alt="screen shot 2015-08-28 at 11 20 22" src="https://cloud.githubusercontent.com/assets/1446145/9544225/b56e5478-4d76-11e5-9982-2a40259bb779.png">

Which I got through `echo "\xE2\x87\x90\x01\xE2\x83\x9E\x02"`

Seems like support on terminals is a bit flaky though.

**Comment by cbandera** [comment]
> Seems like support on terminals is a bit flaky though.

It's not working for me with: `echo -e "\xE2\x87\x90\x01\xE2\x83\x9E\x02"` in the normal Ubuntu Terminal

**Comment by michaeldfallen** [comment]
eh, probably not a good idea, just a bit of fun.

**Comment by pas256** [comment]
This is a great idea

**Comment by eproxus** [comment]
How about "identical" to or "strictly equals"?

```
≡
IDENTICAL TO
Unicode: U+2261, UTF-8: E2 89 A1

≣
STRICTLY EQUIVALENT TO
Unicode: U+2263, UTF-8: E2 89 A3
```

**Comment by anaran** [comment]
@eproxus these don't seem to have [HTML char entity](http://dev.w3.org/html5/html-author/charref) equivalents, which might be nice for mappability.

How about this one?
⩦
    &sdote;
    &#x02A66;
    &#10854;

**Comment by eproxus** [comment]
@anaran Well, there is:

```
≡
&equiv; &Congruent;
&#x02261;
&#8801;
```

Why is HTML character entity codes relevant?

Here are some more alternatives from that page:

```
⊟
&minusb; &boxminus;
&#x0229F;
&#8863;

⊔
&sqcup; &SquareUnion;
&#x02294;
&#8852;

⧉
&boxbox;
&#x029C9;
&#10697;
```

**Comment by anaran** [comment]
@eproxus I like &equiv; &Congruent;

Having an HTML representation for the character can be useful for documentation later.

**Comment by c5f** [comment]
@lorensr this issue can be closed, yes?
