### ISSUE TITLE
Any modifications required for Mac OS?

### ISSUE THREAD

**Issue by grigoryvp** [michaeldfallen/git-prompt#4]
Hello and thanks for amazing work!

All works fine except line length: since you don't escape color codes via additional pair of "\[" and "\]", macos thinks that prompt has much greater length than actually is and wraps text being entered early.

What else do I need to add into my ~/.bashrc to fix this issue? Maybe some flag or general setting is required?

![illustration](https://farm1.staticflickr.com/676/20273122874_61cd088420_o.jpg)

**Comment by michaeldfallen** [comment]
Ah, interesting. I don't fully color codes so I've only done what I can to get it working. Can you suggest fixes that would solve this? The docs online are very dense so hard to grasp.

**Comment by michaeldfallen** [comment]
I've tried adding the `\[` you mentioned around the color codes so for example: 

```
local red_unstaged_prefix="\[\033[1;31m\]"
```

That gives:

<img width="283" alt="screen shot 2015-08-26 at 12 26 40" src="https://cloud.githubusercontent.com/assets/1446145/9492235/99539c92-4bed-11e5-9366-00ed362883ba.png">

seems the `\[` is getting escaped

**Comment by grigoryvp** [comment]
Yep, seems some escaping problems. Need to dig it deeper!

**Comment by michaeldfallen** [comment]
I wouldn't be surprised if my use of printf is messing things around.

**Comment by michaeldfallen** [comment]
Thanks for the pull request btw

**Comment by michaeldfallen** [comment]
Using: `printf '%q' $(./../git-radar/git-radar --bash)` I get:

```
\\[\E[1;30m\\]git:(\\[\E[0m\\]\\[\E[0;37m\\]master\\[\E[0m\\]\\[\E[1;30m\\])\\[\E[0m\\]
```

So the `\` is getting escaped at some point

**Comment by grigoryvp** [comment]
I have tested on my machine, escaping works fine. How did you received this screenshot?

![screenshot](https://cloud.githubusercontent.com/assets/1446145/9492235/99539c92-4bed-11e5-9366-00ed362883ba.png)

Please note, that "\[" and "\]" is a PS1-specific magic, it will not work if just printed from terminal

Can you please check https://github.com/michaeldfallen/git-radar/pull/7 on your machine?

**Comment by michaeldfallen** [comment]
Figured it out, I had my `.bashrc` set to:

``` bash
export PS1='\W$(~/Projects/personal/git-radar/git-radar --bash) '
```

The correct way is:

``` bash
export PS1="\W$(~/Projects/personal/git-radar/git-radar --bash) "
```

I.E. the `'` should be `"`.

**Comment by grigoryvp** [comment]
So if you use double quotes in your `.bashrc` file my pull request works on your machine? Thanks!

**Comment by michaeldfallen** [comment]
Actually it looks like it doesn't work right. So if I use `'` then the prompt gets evaluated every time it renders. If I use `"` git-radar only renders the once, when the prompt first renders. .bashrc doesn't seem to be re-evaluated. 

This might be my machine causing issues. Can you drop me your line where you set your PS1?

**Comment by grigoryvp** [comment]
Indeed where are weird things. If used double quotes  escape codes work correct but evaluates only once (by standard actually), and with single quotes they are messed up.

But it's something inside string returned by git-radar that mess string. If I use:

``` bash
export PS1='\[\e[37m\]\W\[\e[32m\]foo\[\e[33m\] \$ \[\e[37m\]'
```

scape codes work fine. But if `git-radar` is added, its messed up:

``` bash
export PS1='\[\e[37m\]\W\[\e[32m\]$(~/Documents/git-radar/git-radar --bash --fetch)\[\e[33m\] \$ \[\e[37m\]'
```

I don't know why this happens :(

So i used a hack that allows to use double quotes in realtime. This makes things work:

``` bash
make_prompt () {
  PS1="\[\e[37m\]\W\[\e[32m\]$(~/Documents/git-radar/git-radar --bash --fetch)\[\e[33m\] \$ \[\e[37m\]"
}
export PROMPT_COMMAND='make_prompt'
```

**Comment by michaeldfallen** [comment]
Ok, so [this superuser question](http://superuser.com/questions/301353/escape-non-printing-characters-in-a-function-for-a-bash-prompt) explains it. PS1 converts `\[` to `\x01` and `\]` to `\x02`.

When you use `'` to ensure your prompt gets evaluated each time, or use a `\` to escape the `$` in your PS1 for the same purpose:

```
export PS1="\$(git-radar --bash)"
```

then the PS1 doesn't get the chance to convert `\[` to `\x01` etc. The fix is to do the conversion ourselves.

I've pushed a pull request https://github.com/michaeldfallen/git-radar/pull/11, can you check if that works for you? It works for me both in:

``` bash
export PS1='\W\$(~/Projects/personal/git-radar/git-radar --bash) '
```

and 

``` bash
export PS1="\W$(~/Projects/personal/git-radar/git-radar --bash) "
```

**Comment by grigoryvp** [comment]
Seems a very complicated thing. But works like a charm!

**Comment by michaeldfallen** [comment]
Awesome, thanks for the help. Closing.
