### ISSUE TITLE
escaping `$` prevents subexpression evaluation

### ISSUE THREAD

**Issue by maxmurdoch** [michaeldfallen/git-prompt#41]
I'm using zsh on El Capitan (sorry).

`export PROMPT="$(git-radar --zsh --fetch) "` renders the prompt once and then doesn't update. The suggested way to get the subexpression to re-evaluate on each prompt render (`export PROMPT="\$(git-radar --zsh --fetch)"`) renders the raw characters `$(git-radar --zsh --fetch)` for me.

I've tried using backticks and $'$(…)' to evaluate the sub-expression but none have worked so far.

Thanks for making radar and for responding to the issues so well! This one is not urgent at all, so a point in the right direction whenever you've got time would be great :smile:

**Comment by michaeldfallen** [comment]
You can see my zsh prompt config here https://github.com/michaeldfallen/dotfiles/blob/master/zsh/prompt.zsh#L11. That works for me, using the `$'` way. If you post your zshrc I can have a look and try to figure it out.

**Comment by michaeldfallen** [comment]
@maxmurdoch did this work for you? The `$'` style quotes should solve it, in theory:

```
export PROMPT=$'$(git-radar --zsh --fetch) '
```

Closing for now, reopen if this doesn't work.
