### ISSUE TITLE
no-remote-status being ignored?

### ISSUE THREAD

**Issue by cmsimike** [michaeldfallen/git-prompt#49]
I am trying to ignore the remote status section (as checking my current branch against origin/master isn't helpful for me). I can't seem to get the flag to work:

export PS1='[$NC]\u@\h:[$Red]\w[$NC]$(git-radar --bash --fetch --no-remote-status) $ '

Still gives me this output:
mike@compy:~/Development/project git:(𝘮 7 ⇄ 4 develop)

Thanks!

**Comment by michaeldfallen** [comment]
Hi, sorry I was so late to address this. #65 allows you to remove any feature from executing without the need for execution flags like this so I wanted to get it in and kill to birds.

To do this all you need to do is export `GIT_RADAR_FORMAT` with the parts you do want in. e.g.:

```
GIT_RADAR_FORMAT="%{branch}%{ :local}%{ :changes}"
```

In that example I've removed the colour codes and the `git:(` part as well. You can add in whatever bits you want. It supports colour codes as well.
