### ISSUE TITLE
OSX Bash: White space being added before branch-name

### ISSUE THREAD

**Issue by zanona** [michaeldfallen/git-prompt#54]
Hey thanks for git-radar — It feels it's going to really boost my productivity here scanning through changes.

I have tried to install it and somehow and getting some white space before the branch name, any ideas?

Thanks in advance

``` bash
PS1="(\$(git-radar --bash))$"
```

![screen shot 2015-09-03 at 09 30 20](https://cloud.githubusercontent.com/assets/32017/9653867/6ef281ac-521e-11e5-9730-cfc403e149ee.png)

**Comment by michaeldfallen** [comment]
Hi, it's actually not whitespace but black text. Ends up my terminal is set to use "Bright black" for a dark grey colour and most terminals aren't /whoops. On mine it looks like this:
<img width="236" alt="git-radar examples" src="https://cloud.githubusercontent.com/assets/1446145/9698766/96ba8e1a-53bc-11e5-8ca9-5af0a03f24ce.png">

The `git:(` part is causing the whitespace. Sorry about that, but I haven't got around to fixing that colour change.

If you want to fix it and submit a pull request the lines to fix are:

here in bash:
https://github.com/michaeldfallen/git-radar/blob/master/prompt.bash#L9
https://github.com/michaeldfallen/git-radar/blob/master/prompt.bash#L15

and here in zsh:
https://github.com/michaeldfallen/git-radar/blob/master/prompt.zsh#L11
https://github.com/michaeldfallen/git-radar/blob/master/prompt.zsh#L17

Alternatively it looks like your terminal is outputting bright colours as bold text. You could configure your terminal to output 8 brighter colours instead (it's the default for Mac OSX's terminal.app so I foolishly designed the original colour scheme around it.

**Comment by michaeldfallen** [comment]
@zanona see https://github.com/michaeldfallen/git-radar/issues/57#issuecomment-148368864 which explains how to use the new `GIT_RADAR_FORMAT` variable to remove those bits you don't want.
