### ISSUE TITLE
Git-radar doesn't work correctly in my terminal (but before it works)

### ISSUE THREAD

**Issue by n10v** [michaeldfallen/git-prompt#55]
After 0.3 update git-radar starts to work not correctly (both in fish and bash):
![2015-09-04 17 35 47](https://cloud.githubusercontent.com/assets/13235519/9683651/90d1bee2-532b-11e5-94f5-cd89824d0bbb.png)

**Comment by alessandro-fazzi** [comment]
Just installed. Same behaviour.

**Comment by jackmaney** [comment]
Ditto.

**Comment by hallzy** [comment]
yup. Exactly the same

**Comment by arobbins** [comment]
Same for me.

![term](https://cloud.githubusercontent.com/assets/961947/9692244/5d80766e-530d-11e5-85e3-5388063cbffe.jpg)

**Comment by jaybeaton** [comment]
I'm seeing the same thing after upgrading.

**Comment by bogem** [comment]
Fix in progress:
![2015-09-05 7 43 26](https://cloud.githubusercontent.com/assets/13235519/9697312/da6a726c-53a1-11e5-9414-aebe83968c1f.png)

**Comment by bogem** [comment]
Problem in prepare_bash_colors function

**Comment by n10v** [comment]
Problem in readble_branch_name
From 0.3 version git-radar shows colored branch name, but it doesn't work correctly in bash now

**Comment by n10v** [comment]
FIXED
![2015-09-05 8 08 16](https://cloud.githubusercontent.com/assets/13235519/9697390/48ab17f6-53a5-11e5-9b88-61b0622f32e6.png)
