### ISSUE TITLE
Optionally hide "git:"

### ISSUE THREAD

**Issue by timscott** [michaeldfallen/git-prompt#57]
Thanks for git-radar!

The "git:" label is useful for like a day, then it becomes visual noise. Can it be suppressed?

**Comment by n10v** [comment]
+

**Comment by eproxus** [comment]
This is being worked on in #40.

**Comment by michaeldfallen** [comment]
#65 should provide the flexibility to do this. Thoughts?

**Comment by n10v** [comment]
It's good idea

**Comment by michaeldfallen** [comment]
The recent v0.4 release should satisfy this. Now you can just export `GIT_RADAR_FORMAT` and remove the parts you don't need.

Current default bash:

```
GIT_RADAR_FORMAT=" \x01\033[1;30m\x02git:(\x01\033[0m\x02%{remote: }%{branch}%{ :local}\x01\033[1;30m\x02)\x01\033[0m\x02%{ :changes}"
```

Without the `git:(` or `)`:

```
GIT_RADAR_FORMAT=" %{remote: }%{branch}%{ :local}%{ :changes}"
```

The prefix and suffix spaces are in there to space out the prompt, you could remove/replace those if you wanted as well.
