### ISSUE TITLE
Fetches not every 5 minutes?

### ISSUE THREAD

**Issue by hallzy** [michaeldfallen/git-prompt#69]
Hi, I have come across something... it seems that (for me at least) it does not fetch every 5 minutes, but rather, almost immediately.

I notice in the code that there is a record timestamp function that creates a file in the .git directory of a repo, but mine is empty, and with a quick scan of the code I could not find a place that put anything in that file, and thus the timestamp is possible just nothing so the script thinks it needs to fetch always.

Has anyone else seen this?

Not that I am complaining, because I think I like it this way anyways, but just something I observed.

**Comment by hallzy** [comment]
My mistake, on further inspection of the code, it appears that the script is trying to check some creation, or modified statistic for the lastupdatetime file, except that what it tries to do is returning 0 instead of the time.

I am using Ubuntu

**Comment by hallzy** [comment]
For ubuntu I need to replace line 134 of radar-base.sh... I tried this:

printf '%s' "$(stat -c%Z "$(dot_git)/lastupdatetime" 2>/dev/null || printf '%s' "0")"

and that worked

I assume that the statement that is already there works on another OS? I am unsure how to make this line OS specific so that it only executes on specific OS's

**Comment by hallzy** [comment]
What does the stat -f%m that is already in the script work with?

**Comment by michaeldfallen** [comment]
`stat -f%m` is the correct parameter for the version of stat provided by default by OSX. Seems stat isn't the same on OSX and Ubuntu. I've checked and `gstat`, GNU version of stat provided by coreutils supports the `gstat -c%Z` flag that you've mentioned above.

It's annoying but we can deal with it. The brew formula already installs coreutils so we can switch fairly easily to `gstat` for Mac and `stat` for everything else.

**Comment by michaeldfallen** [comment]
Nice catch :+1:

**Comment by hallzy** [comment]
Thanks :)

Would my pull request #77 fix this issue? I do not have a Mac to test it, but it is working for me on Ubuntu.

**Comment by hallzy** [comment]
Closing because PR #79 was merged to fix this.
