### ISSUE TITLE
odd sed error on branches named with multiple / characters

### ISSUE THREAD

**Issue by c5f** [michaeldfallen/git-prompt#75]
I am receiving this error:

```
sed: 1: "s/%{\(\([^%^{^}]*\)\:\) ...": bad flag in substitute command: 't'
```

This is my PS1:

``` bash
export PS1="\[\033[01;32m\]\j\[\033[00m\]|\[\033[01;34m\]\W\[\033[00m\] \$(git-radar --bash --fetch) 🍉 ";
```

---

This error occurs sporadically in and out of tmux, and I fully acknowledge that some other utility may be causing it.  Any help is appreciated.

Cheers :beers:

**Comment by michaeldfallen** [comment]
This'll output a lot of stuff but can you run `set -xv` in your shell and post the output? I need to know which sed command is causing the issue. It's probably the `render_prompt` function but without more I can't say whats going on.

BTW, you'll want to run `set +xv` afterwards to deactivate the debug output.

**Comment by c5f** [comment]
I didn't want to paste my entire shell output because it was all of the function sourcing for nvm/rvm/homebrew/completion/etc.  The sed error above only appeared at the very end of the debug output from `source ~/.bash_profile` after everything else had run.

```
++ git-radar --bash --fetch
sed: 1: "s/%{\(\([^%^{^}]*\)\:\) ...": bad flag in substitute command: 't'
```

This only happens when I am on a branch with two `/` characters in the branch name, but my team namespaces feature branches, so that happens quite frequently.

```
0|repo  git:(𝘮 7 ⇄ 408 develop)🍉 git checkout -b feature/example
git checkout -b feature/example
+ hub checkout -b feature/example
Switched to a new branch 'feature/example'
git-radar --bash --fetch
++ git-radar --bash --fetch
0|repo  git:(upstream ⚡ feature/example)🍉 git checkout -b feature/somebody/test
git checkout -b feature/somebody/test
+ hub checkout -b feature/somebody/test
Switched to a new branch 'feature/somebody/test'
git-radar --bash --fetch
++ git-radar --bash --fetch
sed: 1: "s/%{\(\([^%^{^}]*\)\:\) ...": bad flag in substitute command: 't'
0|repo 🍉 git checkout feature/example
git checkout feature/example
+ hub checkout feature/example
Switched to branch 'feature/example'
git-radar --bash --fetch
++ git-radar --bash --fetch
0|repo  git:(upstream ⚡ feature/example)🍉
```

**Comment by c5f** [comment]
I also realize this probably isn't what you asked for with `set -xv`, but this is all the output I get.

**Comment by jhunold** [comment]
Can you try #78 and see if this fixes the issue?

**Comment by c5f** [comment]
@jhunold @michaeldfallen #78 solves my problemo thanks. :tada::confetti_ball::dolphin::whale:

**Comment by michaeldfallen** [comment]
Well that made it easy to merge #78 :-)

**Comment by michaeldfallen** [comment]
Closing.
