### ISSUE TITLE
Made a new lightweight stable version of git-radar

### ISSUE THREAD

**Issue by n10v** [michaeldfallen/git-prompt#84]
Just made a new lightweight stable version of git-radar 0.3.2
Only for Mac OS X and for fish/bash
Link: https://github.com/bogem/mini-git-radar
Hope, someone like it

**Comment by michaeldfallen** [comment]
Nice :+1:.

I'll close this as it's not an issue to be fixed but would you mind submitting a pull request that adds a link to the README please? I think it's only fair to cross link to your work :smile:.

**Comment by n10v** [comment]
Ok, I'll make it now :)
