### ISSUE TITLE
Unhandled git error when a tracked upstream branch is removed

### ISSUE THREAD

**Issue by c5f** [michaeldfallen/git-prompt#88]
```
git checkout -b some-feature
git push -u some-remote some-feature
git push some-remote :some-feature
```

yields the following output whenever `git-radar` is called on the branch with the missing upstream:

```
fatal: ambiguous argument 'some-remote/some-feature...HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
Fatal: ambiguous argument 'some-remote/some-feature...HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```

The example is a silly chain of three commands to elicit this behavior, but I don't think having tracked branches deleted from remotes is an uncommon occurrence.

**Comment by hallzy** [comment]
See #86. The error looks similar and can probably be resolved with the same 2>/dev/null appending as specified there. Looks like @michaeldfallen is adding it.

**Comment by michaeldfallen** [comment]
I'm thinking squash the error as you have and create a "not upstream" indicator. Taking functionality away from the "remote commits" indicator (which honestly shouldn't be doing that not upstream functionality if we were being pure) and combines it with a "ok my upstream is configured but does it actually exist?" check.
